= Monte-Carlo-Simulation einer Fahrradwerkstatt

_Author: Alexander Schulz, Datum: 2025-05-01, Matr.-Nr.: 55297_

== Modellbeschreibung:
**Grundparameter:**

- Monatliche Reparaturanfragen folgen einem saisonalen Muster.
- Höhepunkt in den Frühlings- und Sommermonaten während der Radsaison.  
- Rückgang im Winter (außer für Wartungen vor dem Frühling).  
- Zusätzlich unabhängig beeinflusst von der durchschnittlichen monatlichen Niederschlagsmenge.
- Reparaturzeit ist gleichmäßig verteilt zwischen 1 und 3 Stunden.

== Zielfunktionen:
. Optimierung des Gewinns
. Optimierung der Mitarbeiteranzahl
. Optimierung der Kundenzufriedenheit

== Zu beantwortende Frage:

Wie viele Mitarbeiter muss ich pro Monat einstellen, um den Gewinn zu maximieren?

== Vergleich der Ergebnisse

Konstanter Mitarbeiterbestand (5 Mitarbeiter)
include::src/bike_repair_shop_results_1746105786.575884.png[]

Optimater Mitarbeiterbestand pro Monat

[2, 3, 6, 9, 11, 13, 12, 11, 9, 6, 3, 4]

include::src/bike_repair_shop_results_1746105787.547169.png[]

== Schlussfolgerung
Die Simulation zeigt, dass die Anzahl der Reparaturanfragen stark saisonal schwankt.
Die Anzahl der Reparaturaufträge ist im Sommer am höchsten, während sie im Winter am niedrigsten ist.
Daher ist es sinnvoll, die Anzahl der Mitarbeiter entsprechend der Ergebnisse der Simulation zu variieren.

== Technische Details:

=== Implementierung der Simulation:

* Tägliche Reparaturanfragen schwanken zufällig um den saisonalen Mittelwert.
- Saisonaler Mittelwert (Basisparameter) = Anfragen pro Tag pro Monat
- Zusätzlicher Einfluss durch den Wetterfaktor (Niederschlagsmenge)
- Wetterfaktor anhand der tägliche Schwankung des Niederschlags (normalverteilt)
- Poisson Verteilung für das zufällige Eintreffen der Reparaturanfragen pro Tag


[,python]
----
include::src/main.py[lines="109..115"]
----

[,python]
----
include::src/main.py[lines="50..63"]
----


* Reparaturdauer pro Fahrrad folgt einer Wahrscheinlichkeitsverteilung.

[,python]
----
include::src/main.py[lines="65..68"]
----
* Benötigte Ersatzteile pro Reparatur sind probabilistisch bestimmt.

[,python]
----
include::src/main.py[lines="70..78"]
----
